server:
  servlet:
    context-path: '/api'
  port: 8080
spring:
  application:
    name: 'kafka-consumer'
  kafka:
    consumer:
      # Kafka IP address and port
      bootstrap-servers: localhost:9092
      group-id: backend-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      topic: heartbeat
      partition: 3
      properties:
        # Spring generates appropriate JSON deserializer mappings according to these definitions
        spring:
          json:
            trusted:
              packages: '*'
            value:
              default:
                type: 'com.ouva.demo.dto.HeartbeatKafkaRecord'
    listener:
      # Use 'concurrency' number of consumers to handle incoming messages.
      # (Number of partitions needs to be greater or equals to this value to make it work!)
      concurrency: 3
  data:
    mongodb:
      authentication-database: admin
      host: localhost
      port: 27017
      database: ouvadb
      username: root
      password: secret
